/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnotationRenderer: typeof import('./theme/components/Layout/AnnotationRenderer.vue')['default']
    AppleIcon: typeof import('./theme/components/Layout/AppleIcon.vue')['default']
    ArchiveCount: typeof import('./theme/components/ArchiveCount.vue')['default']
    ArticleMetadata: typeof import('./theme/components/ArticleMetadata.vue')['default']
    CarouselComponent: typeof import('./theme/components/CarouselComponent.vue')['default']
    ClickHearts: typeof import('./theme/components/Layout/ClickHearts.vue')['default']
    ClientOnly: typeof import('./theme/components/ClientOnly.vue')['default']
    Confetti: typeof import('./theme/components/Confetti.vue')['default']
    CustomButton: typeof import('./theme/components/CustomButton.vue')['default']
    CustomIcon: typeof import('./theme/components/CustomIcon.vue')['default']
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    FontSettingsPlugin: typeof import('./theme/components/Layout/FontSettingsPlugin.vue')['default']
    Gdt: typeof import('./theme/components/gdt.vue')['default']
    HomeUnderline: typeof import('./theme/components/HomeUnderline.vue')['default']
    Interval: typeof import('./theme/components/interval.vue')['default']
    LoadingAnimation: typeof import('./theme/components/LoadingAnimation.vue')['default']
    MarkerText: typeof import('./theme/components/MarkerText.vue')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    NavMenu: typeof import('./theme/components/NavMenu.vue')['default']
    PdfViewer: typeof import('./theme/components/PdfViewer.vue')['default']
    PrevNextNav: typeof import('./theme/components/PrevNextNav.vue')['default']
    QindFooter: typeof import('./theme/components/Layout/QindFooter.vue')['default']
    QindHero: typeof import('./theme/components/Layout/QindHero.vue')['default']
    ReaderText: typeof import('./theme/components/ReaderText.vue')['default']
    ReadingProgress: typeof import('./theme/components/Layout/ReadingProgress.vue')['default']
    ReadingProgress_mobile: typeof import('./theme/components/Layout/ReadingProgress_mobile.vue')['default']
    SidebarTrigger: typeof import('./theme/components/SidebarTrigger.vue')['default']
    SmoothDetails: typeof import('./theme/components/SmoothDetails.vue')['default']
    SnowEffect: typeof import('./theme/components/Layout/SnowEffect.vue')['default']
    SnowTrigger: typeof import('./theme/components/Layout/SnowTrigger.vue')['default']
    Spotlight: typeof import('./theme/components/Spotlight/index.vue')['default']
    SpotlightHover: typeof import('./theme/components/Spotlight/components/SpotlightHover.vue')['default']
    TextSelectionMenu: typeof import('./theme/components/Layout/TextSelectionMenu.vue')['default']
    TypingText: typeof import('./theme/components/TypingText.vue')['default']
    VideoLink: typeof import('./theme/components/VideoLink.vue')['default']
    YAMLCarousel: typeof import('./theme/components/YAMLCarousel.vue')['default']
  }
}
