/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnotationRenderer: typeof import('./theme/components/AnnotationRenderer.vue')['default']
    AppleIcon: typeof import('./theme/components/AppleIcon.vue')['default']
    ArchiveCount: typeof import('./theme/components/ArchiveCount.vue')['default']
    ArticleMetadata: typeof import('./theme/components/ArticleMetadata.vue')['default']
    'Bi:github': typeof import('~icons/bi/github')['default']
    CarouselComponent: typeof import('./theme/components/CarouselComponent.vue')['default']
    ClickHearts: typeof import('./theme/components/ClickHearts.vue')['default']
    ClientOnly: typeof import('./theme/components/ClientOnly.vue')['default']
    Confetti: typeof import('./theme/components/Confetti.vue')['default']
    CustomButton: typeof import('./theme/components/CustomButton.vue')['default']
    CustomIcon: typeof import('./theme/components/CustomIcon.vue')['default']
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    'Fe:youtube': typeof import('~icons/fe/youtube')['default']
    FontSettingsPlugin: typeof import('./theme/components/FontSettingsPlugin.vue')['default']
    Gdt: typeof import('./theme/components/gdt.vue')['default']
    HomeUnderline: typeof import('./theme/components/HomeUnderline.vue')['default']
    Interval: typeof import('./theme/components/interval.vue')['default']
    'Logos:reactQueryIcon': typeof import('~icons/logos/react-query-icon')['default']
    MarkerText: typeof import('./theme/components/MarkerText.vue')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    NavMenu: typeof import('./theme/components/NavMenu.vue')['default']
    NavVisitor: typeof import('./theme/components/NavVisitor.vue')['default']
    PdfViewer: typeof import('./theme/components/PdfViewer.vue')['default']
    'Ph:planetFill': typeof import('~icons/ph/planet-fill')['default']
    PrevNextNav: typeof import('./theme/components/PrevNextNav.vue')['default']
    QindFooter: typeof import('./theme/components/QindFooter.vue')['default']
    QindHero: typeof import('./theme/components/QindHero.vue')['default']
    ReaderText: typeof import('./theme/components/ReaderText.vue')['default']
    ReadingProgress: typeof import('./theme/components/ReadingProgress.vue')['default']
    SidebarTrigger: typeof import('./theme/components/SidebarTrigger.vue')['default']
    'SimpleIcons:markdown': typeof import('~icons/simple-icons/markdown')['default']
    'SimpleIcons:zhihu': typeof import('~icons/simple-icons/zhihu')['default']
    'SkillIcons:reactDark': typeof import('~icons/skill-icons/react-dark')['default']
    'SkillIcons:stackoverflowDark': typeof import('~icons/skill-icons/stackoverflow-dark')['default']
    'SkillIcons:typescript': typeof import('~icons/skill-icons/typescript')['default']
    'SkillIcons:vercelDark': typeof import('~icons/skill-icons/vercel-dark')['default']
    SmoothDetails: typeof import('./theme/components/SmoothDetails.vue')['default']
    SnowEffect: typeof import('./theme/components/SnowEffect.vue')['default']
    SnowTrigger: typeof import('./theme/components/SnowTrigger.vue')['default']
    Spotlight: typeof import('./theme/components/Spotlight/index.vue')['default']
    SpotlightHover: typeof import('./theme/components/Spotlight/components/SpotlightHover.vue')['default']
    'Tabler:brandBilibili': typeof import('~icons/tabler/brand-bilibili')['default']
    'Tabler:brandJuejin': typeof import('~icons/tabler/brand-juejin')['default']
    'Teenyicons:nextjsSolid': typeof import('~icons/teenyicons/nextjs-solid')['default']
    TextSelectionMenu: typeof import('./theme/components/TextSelectionMenu.vue')['default']
    TypingText: typeof import('./theme/components/TypingText.vue')['default']
    'Uiw:weixin': typeof import('~icons/uiw/weixin')['default']
    VideoLink: typeof import('./theme/components/VideoLink.vue')['default']
    'VscodeIcons:fileTypeBun': typeof import('~icons/vscode-icons/file-type-bun')['default']
    YAMLCarousel: typeof import('./theme/components/YAMLCarousel.vue')['default']
  }
}
